# =============================================================================
# Program      : 01_exp1_kurtosis_separability.py
# Version      : 1.0
# Description  : Experiment 1 — Kurtosis Separability Analysis.
#
#                Establishes that subband kurtosis is a statistically
#                significant discriminant between real and synthetic speech
#                across cochlear-frequency subbands, before any classifier
#                is trained.
#
# INPUT:
#                  Google Drive project folder (downloaded to local):
#                    hos_features_train.h5   — 25,380 utterances × 2,496 dims generated by 05_exp5_hos_robustness.py
#                  Google Drive:
#                    /content/drive/MyDrive/datasets/
#                      ASVspoof2019_LA_cm_protocols/
#                        ASVspoof2019.LA.cm.train.trn.txt
#
# FEATURE LAYOUT (per utterance, 2,496-dim vector):
#                  Per channel (24 channels, 104 dims each, channel-interleaved):
#                    dims [ch*104 + 0:4]   kurtosis fine-structure
#                                          (mean, var, p10, p90)
#                    dims [ch*104 + 4:8]   kurtosis envelope
#                                          (mean, var, p10, p90)
#                    dims [ch*104 + 8:104] bispectrum diagonal
#                                          (32 lags × 3 pooling stats)
#
# PIPELINE:
#                  Step 1  Download hos_features_train.h5 from Google Drive
#                  Step 2  Parse train protocol for bonafide/spoof labels
#                  Step 3  Extract kurtosis fine-structure and envelope
#                          (mean pooling stat only) per channel per utterance
#                  Step 4  Compute per-channel Cohen's d effect size and
#                          Mann-Whitney U test (with Bonferroni correction)
#                  Step 5  Generate figures and save results JSON
#                  Step 6  Upload all outputs to Google Drive
#
# OUTPUT FILES (uploaded to Google Drive PROJECT_DIR):
#                  exp1_separability.json
#                      Per-channel Cohen's d, Mann-Whitney U, p-values,
#                      Bonferroni-corrected significance flags,
#                      channel centre frequencies
#                  fig_01_01_cohens_d_heatmap.png
#                      24×2 heatmap of Cohen's d (fine-structure, envelope)
#                      x-axis: channel index, y-axis: component
#                  fig_01_02_kurtosis_violin.png
#                      Per-channel violin plots of kurtosis fine-structure mean,
#                      bonafide vs spoof (top 8 most discriminative channels)
#                  fig_01_03_kurtosis_meanprofile.png
#                      Mean kurtosis fine-structure and envelope vs channel
#                      for bonafide and spoof, with ±1 std shading
#                  fig_01_04_cohens_d_barplot.png
#                      Cohen's d ranked bar chart for fine-structure channels,
#                      colour-coded by significance after Bonferroni correction
#
# GPU Required : NO
# Dependencies : numpy, scipy, matplotlib, h5py, tqdm
#
# Change Log   :
#   v1.0  2026-06-03  Initial version
# =============================================================================

# !pip install numpy scipy matplotlib h5py tqdm

# =============================================================================
# SECTION 0 — Imports and Configuration
# =============================================================================

import os
import json
import time
import shutil
import warnings
import numpy as np
import scipy.stats as st
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import TwoSlopeNorm
import h5py
from tqdm import tqdm

warnings.filterwarnings('ignore')

# --- Google Drive Configuration ---
PROJECT_DIR = "/content/drive/MyDrive/paper/Subband_Kurtosis/"  # Persistent storage

# --- Paths ---
DRIVE_PROTOCOL  = ("/content/drive/MyDrive/datasets/"
                   "ASVspoof2019_LA_cm_protocols/"
                   "ASVspoof2019.LA.cm.train.trn.txt")
LOCAL_DIR       = "/content/exp1_work"
os.makedirs(LOCAL_DIR, exist_ok=True)

# --- Feature layout constants (must match 05_exp5_hos_robustness_v01.py) ---
N_CHANNELS      = 24
DIMS_PER_CHAN   = 104   # 4 (kurt_fine) + 4 (kurt_env) + 96 (bispec)
KURT_FINE_OFFSET = 0   # within channel block: mean at +0, var +1, p10 +2, p90 +3
KURT_ENV_OFFSET  = 4   # within channel block: mean at +4, var +5, p10 +6, p90 +7
POOL_MEAN_IDX   = 0    # mean is the first pooling stat
POOL_VAR_IDX    = 1
POOL_P10_IDX    = 2
POOL_P90_IDX    = 3

# --- ERB filterbank centre frequencies (reproduced from Exp 5 pipeline) ---
def _hz_from_erb_rate(erb_rate):
    return (10 ** (erb_rate / 21.366) - 1) / 0.004368

def get_channel_centres(n=N_CHANNELS, fmin=80.0, fmax=8000.0):
    erb_min = 21.366 * np.log10(1 + 0.004368 * fmin)
    erb_max = 21.366 * np.log10(1 + 0.004368 * fmax)
    erb_rates = np.linspace(erb_min, erb_max, n)
    return np.array([_hz_from_erb_rate(r) for r in erb_rates])

CHANNEL_CENTRES_HZ = get_channel_centres()

# --- Plot style ---
plt.rcParams.update({
    'font.family'      : 'DejaVu Sans',
    'font.size'        : 11,
    'axes.titlesize'   : 12,
    'axes.titleweight' : 'bold',
    'axes.labelsize'   : 11,
    'xtick.labelsize'  : 8,
    'ytick.labelsize'  : 9,
    'legend.fontsize'  : 9,
    'figure.dpi'       : 300,
})

C_BON  = '#1565C0'   # bonafide — blue
C_SPO  = '#B71C1C'   # spoof    — red

# =============================================================================
# SECTION 1 — Google Drive Helpers
# =============================================================================

def ensure_project_dir():
    """Create project directory in Google Drive if it doesn't exist."""
    os.makedirs(PROJECT_DIR, exist_ok=True)

def save_to_drive(local_path, remote_name, retries=3):
    """Copy a local file to Google Drive project folder."""
    ensure_project_dir()
    dest_path = os.path.join(PROJECT_DIR, remote_name)
    for attempt in range(retries):
        try:
            shutil.copy2(local_path, dest_path)
            print(f"  [DRIVE OK] {local_path}  →  {dest_path}")
            return
        except Exception as e:
            print(f"  [DRIVE FAIL] attempt {attempt+1}: {e}")
            time.sleep(2)
    print(f"  [DRIVE FAILED] {remote_name}")

def load_from_drive(remote_name, local_path):
    """Copy a file from Google Drive project folder to local path."""
    ensure_project_dir()
    src_path = os.path.join(PROJECT_DIR, remote_name)
    if os.path.exists(src_path):
        try:
            shutil.copy2(src_path, local_path)
            print(f"  [DRIVE OK] {src_path}  →  {local_path}")
            return True
        except Exception as e:
            print(f"  [DRIVE FAIL] copy from {src_path}: {e}")
            return False
    else:
        print(f"  [DRIVE MISSING] {src_path} not found")
        return False

def download_h5_from_drive(remote_name, local_path):
    """Download HDF5 from Google Drive with validation."""
    if os.path.exists(local_path):
        try:
            with h5py.File(local_path, 'r') as hf:
                n = len(hf.keys())
            print(f"Local HDF5 found: {n} utterances. Skipping download.")
            return
        except Exception:
            print("Local HDF5 corrupt. Re-downloading.")
            os.remove(local_path)

    print(f"Downloading {remote_name} from Google Drive ...")
    if load_from_drive(remote_name, local_path):
        # Validate
        with h5py.File(local_path, 'r') as hf:
            n = len(hf.keys())
        print(f"Downloaded and validated: {n} utterances  "
              f"({os.path.getsize(local_path)/1e6:.1f} MB)")
    else:
        print(f"[ERROR] Could not download {remote_name} from Drive.")
        sys.exit(1)

# =============================================================================
# SECTION 2 — Protocol Parsing
# =============================================================================

def parse_train_protocol(txt_path):
    """Returns {utt_id: label} where 0=bonafide, 1=spoof."""
    labels = {}
    with open(txt_path) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 5:
                continue
            labels[parts[1]] = 0 if parts[4] == "bonafide" else 1
    bon = sum(1 for v in labels.values() if v == 0)
    spo = sum(1 for v in labels.values() if v == 1)
    print(f"Protocol: {len(labels)} utterances  "
          f"(bonafide={bon}, spoof={spo})")
    return labels

# =============================================================================
# SECTION 3 — Feature Extraction from HDF5
# =============================================================================

def load_kurtosis_from_h5(h5_path, labels_dict):
    """
    Loads per-channel kurtosis (mean pooling stat) from HDF5.

    Returns:
      kurt_fine  : (N, 24) float32 — fine-structure kurtosis mean per channel
      kurt_env   : (N, 24) float32 — envelope kurtosis mean per channel
      y          : (N,) int32      — 0=bonafide, 1=spoof
      utt_ids    : list of str
    """
    kurt_fine_list, kurt_env_list, y_list, ids_list = [], [], [], []

    with h5py.File(h5_path, 'r') as hf:
        utt_ids = list(hf.keys())
        for utt_id in tqdm(utt_ids, desc="Loading HDF5", ncols=80):
            label = labels_dict.get(utt_id, -1)
            if label == -1:
                continue
            feat = hf[utt_id]['feat'][:]          # (2496,)

            # Extract kurtosis mean per channel using layout map
            fine_means = np.array([
                feat[ch * DIMS_PER_CHAN + KURT_FINE_OFFSET + POOL_MEAN_IDX]
                for ch in range(N_CHANNELS)
            ], dtype=np.float32)

            env_means = np.array([
                feat[ch * DIMS_PER_CHAN + KURT_ENV_OFFSET + POOL_MEAN_IDX]
                for ch in range(N_CHANNELS)
            ], dtype=np.float32)

            kurt_fine_list.append(fine_means)
            kurt_env_list.append(env_means)
            y_list.append(label)
            ids_list.append(utt_id)

    kurt_fine = np.array(kurt_fine_list, dtype=np.float32)
    kurt_env  = np.array(kurt_env_list,  dtype=np.float32)
    y         = np.array(y_list,         dtype=np.int32)

    bon = (y == 0).sum()
    spo = (y == 1).sum()
    print(f"Loaded: {len(y)} utterances  "
          f"(bonafide={bon}, spoof={spo})  "
          f"Shape: {kurt_fine.shape}")
    return kurt_fine, kurt_env, y, ids_list

# =============================================================================
# SECTION 4 — Statistical Analysis
# =============================================================================

def cohens_d(x1, x2):
    """
    Cohen's d: standardised mean difference.
    Uses pooled standard deviation (Hedges' formulation for unequal N).
    Positive values mean x1 > x2.
    """
    n1, n2   = len(x1), len(x2)
    mean_diff = np.mean(x1) - np.mean(x2)
    pooled_std = np.sqrt(
        ((n1 - 1) * np.var(x1, ddof=1) + (n2 - 1) * np.var(x2, ddof=1))
        / (n1 + n2 - 2)
    )
    if pooled_std < 1e-12:
        return 0.0
    return float(mean_diff / pooled_std)

def separability_analysis(kurt_matrix, y, component_name):
    """
    Per-channel separability: Cohen's d + Mann-Whitney U + Bonferroni.

    Args:
      kurt_matrix : (N, 24) kurtosis values
      y           : (N,) labels (0=bonafide, 1=spoof)
      component_name: 'fine_structure' or 'envelope'

    Returns dict with per-channel stats.
    """
    bon_idx = np.where(y == 0)[0]
    spo_idx = np.where(y == 1)[0]
    n_tests  = N_CHANNELS
    alpha    = 0.05
    alpha_bf = alpha / n_tests   # Bonferroni threshold

    results = {
        'component'    : component_name,
        'n_bonafide'   : int(len(bon_idx)),
        'n_spoof'      : int(len(spo_idx)),
        'n_tests'      : n_tests,
        'alpha_bonferroni': float(alpha_bf),
        'channels'     : []
    }

    print(f"\n  {component_name}:")
    print(f"  {'Ch':>3}  {'Freq(Hz)':>9}  {'d':>7}  {'p-raw':>10}  "
          f"{'p-BF':>10}  {'sig':>4}  "
          f"{'mean_bon':>9}  {'mean_spo':>9}")
    print("  " + "-" * 75)

    for ch in range(N_CHANNELS):
        bon_vals = kurt_matrix[bon_idx, ch]
        spo_vals = kurt_matrix[spo_idx, ch]

        d    = cohens_d(bon_vals, spo_vals)
        stat, p_raw = st.mannwhitneyu(bon_vals, spo_vals,
                                       alternative='two-sided')
        p_bf  = min(p_raw * n_tests, 1.0)   # Bonferroni-corrected p
        sig   = p_bf < alpha

        ch_result = {
            'channel_idx'       : ch,
            'centre_freq_hz'    : float(CHANNEL_CENTRES_HZ[ch]),
            'cohens_d'          : round(d, 4),
            'mannwhitney_u'     : float(stat),
            'p_raw'             : float(p_raw),
            'p_bonferroni'      : float(p_bf),
            'significant'       : bool(sig),
            'mean_bonafide'     : float(np.mean(bon_vals)),
            'mean_spoof'        : float(np.mean(spo_vals)),
            'std_bonafide'      : float(np.std(bon_vals)),
            'std_spoof'         : float(np.std(spo_vals)),
            'median_bonafide'   : float(np.median(bon_vals)),
            'median_spoof'      : float(np.median(spo_vals)),
        }
        results['channels'].append(ch_result)

        sig_str = "***" if sig else "   "
        print(f"  {ch:>3}  {CHANNEL_CENTRES_HZ[ch]:>9.0f}  "
              f"{d:>7.3f}  {p_raw:>10.2e}  {p_bf:>10.2e}  "
              f"{sig_str:>4}  "
              f"{np.mean(bon_vals):>9.3f}  {np.mean(spo_vals):>9.3f}")

    n_sig = sum(1 for c in results['channels'] if c['significant'])
    print(f"\n  Significant channels (Bonferroni): {n_sig}/{N_CHANNELS}")

    return results

# =============================================================================
# SECTION 5 — Figures
# =============================================================================

def fig_cohens_d_heatmap(fine_results, env_results, out_path):
    """
    Figure 1: 2×24 heatmap of Cohen's d values.
    Rows: fine-structure, envelope. Columns: channels (labelled in Hz).
    """
    d_fine = np.array([c['cohens_d'] for c in fine_results['channels']])
    d_env  = np.array([c['cohens_d'] for c in env_results['channels']])
    matrix = np.vstack([d_fine, d_env])   # (2, 24)

    # Diverging colormap centred at 0
    vmax = max(abs(matrix).max(), 0.5)
    norm = TwoSlopeNorm(vmin=-vmax, vcenter=0, vmax=vmax)

    fig, ax = plt.subplots(figsize=(13, 2.8))
    im = ax.imshow(matrix, aspect='auto', cmap='RdBu_r', norm=norm)

    # x-axis: channel frequencies (rounded to nearest 10 Hz)
    freq_labels = [f"{int(round(f/10)*10)}" for f in CHANNEL_CENTRES_HZ]
    ax.set_xticks(range(N_CHANNELS))
    ax.set_xticklabels(freq_labels, rotation=45, ha='right', fontsize=7)
    ax.set_yticks([0, 1])
    ax.set_yticklabels(['Fine-structure', 'Envelope'], fontsize=10)
    ax.set_xlabel("Gammatone Channel Centre Frequency (Hz)")
    ax.set_title("Cohen's $d$ — Bonafide vs. Spoof Kurtosis per Subband",
                 pad=8)

    # Annotate each cell with d value
    for i in range(2):
        for j in range(N_CHANNELS):
            val = matrix[i, j]
            color = 'white' if abs(val) > 0.6 * vmax else 'black'
            ax.text(j, i, f'{val:.2f}', ha='center', va='center',
                    fontsize=6, color=color)

    # Mark significance with asterisk below heatmap
    for j, ch in enumerate(fine_results['channels']):
        if ch['significant']:
            ax.text(j, 1.52, '*', ha='center', va='bottom',
                    fontsize=9, color='black', fontweight='bold')

    cbar = plt.colorbar(im, ax=ax, fraction=0.02, pad=0.02)
    cbar.set_label("Cohen's $d$", fontsize=9)
    fig.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {os.path.basename(out_path)}")


def fig_kurtosis_violin(kurt_fine, y, fine_results, out_path):
    """
    Figure 2: Violin plots for the 8 most discriminative channels
    (by |Cohen's d| on fine-structure kurtosis).
    """
    # Rank channels by |d|
    d_vals   = np.array([abs(c['cohens_d']) for c in fine_results['channels']])
    top8_idx = np.argsort(d_vals)[::-1][:8]

    bon_idx = np.where(y == 0)[0]
    spo_idx = np.where(y == 1)[0]

    fig, axes = plt.subplots(2, 4, figsize=(13, 6), sharey=False)
    axes = axes.flatten()

    for rank, ch in enumerate(top8_idx):
        ax    = axes[rank]
        bon_v = kurt_fine[bon_idx, ch]
        spo_v = kurt_fine[spo_idx, ch]

        # Clip extreme outliers for display only
        p1, p99 = np.percentile(np.concatenate([bon_v, spo_v]), [1, 99])
        bon_v_clip = np.clip(bon_v, p1, p99)
        spo_v_clip = np.clip(spo_v, p1, p99)

        parts = ax.violinplot([bon_v_clip, spo_v_clip],
                               positions=[0, 1],
                               showmedians=True,
                               showextrema=False)

        parts['bodies'][0].set_facecolor(C_BON)
        parts['bodies'][0].set_alpha(0.7)
        parts['bodies'][1].set_facecolor(C_SPO)
        parts['bodies'][1].set_alpha(0.7)
        parts['cmedians'].set_color('black')
        parts['cmedians'].set_linewidth(1.5)

        d_ch  = fine_results['channels'][ch]['cohens_d']
        sig   = fine_results['channels'][ch]['significant']
        freq  = CHANNEL_CENTRES_HZ[ch]
        title = (f"Ch {ch}  ({freq:.0f} Hz)\n"
                 f"$d$={d_ch:.2f}{'*' if sig else ''}")
        ax.set_title(title, fontsize=9)
        ax.set_xticks([0, 1])
        ax.set_xticklabels(['Bonafide', 'Spoof'], fontsize=8)
        ax.set_ylabel("Kurtosis (fine-str.)", fontsize=7)
        ax.grid(True, axis='y', linestyle='--', alpha=0.4)

    fig.suptitle("Kurtosis Fine-Structure Distribution — Top 8 Discriminative Channels",
                 fontsize=11, fontweight='bold', y=1.01)
    bon_patch = mpatches.Patch(color=C_BON, alpha=0.7, label='Bonafide')
    spo_patch = mpatches.Patch(color=C_SPO, alpha=0.7, label='Spoof')
    fig.legend(handles=[bon_patch, spo_patch], loc='upper right',
               fontsize=9, bbox_to_anchor=(1.0, 1.0))
    fig.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {os.path.basename(out_path)}")


def fig_mean_profile(kurt_fine, kurt_env, y, out_path):
    """
    Figure 3: Mean kurtosis profile vs channel frequency for bonafide and spoof.
    Two panels: fine-structure (top), envelope (bottom).
    """
    bon_idx = np.where(y == 0)[0]
    spo_idx = np.where(y == 1)[0]
    freqs   = CHANNEL_CENTRES_HZ

    fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=True)

    for ax, kurt_mat, comp_label in zip(
            axes,
            [kurt_fine, kurt_env],
            ['Fine-structure kurtosis', 'Envelope kurtosis']):

        bon_mean = kurt_mat[bon_idx].mean(axis=0)
        bon_std  = kurt_mat[bon_idx].std(axis=0)
        spo_mean = kurt_mat[spo_idx].mean(axis=0)
        spo_std  = kurt_mat[spo_idx].std(axis=0)

        ax.fill_between(freqs, bon_mean - bon_std, bon_mean + bon_std,
                        color=C_BON, alpha=0.15)
        ax.fill_between(freqs, spo_mean - spo_std, spo_mean + spo_std,
                        color=C_SPO, alpha=0.15)
        ax.plot(freqs, bon_mean, 'o-', color=C_BON, lw=1.8,
                ms=4, label='Bonafide')
        ax.plot(freqs, spo_mean, 's--', color=C_SPO, lw=1.8,
                ms=4, label='Spoof')
        ax.axhline(0, color='black', lw=0.7, ls=':', alpha=0.5)
        ax.set_ylabel(f"Mean excess {comp_label.lower()}")
        ax.set_title(comp_label)
        ax.legend(fontsize=9)
        ax.grid(True, linestyle='--', alpha=0.35)
        ax.set_xscale('log')

    axes[-1].set_xlabel("Channel Centre Frequency (Hz)")
    fig.suptitle("Mean Subband Kurtosis Profile: Bonafide vs Spoof",
                 fontsize=12, fontweight='bold')
    fig.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {os.path.basename(out_path)}")


def fig_cohens_d_barplot(fine_results, env_results, out_path):
    """
    Figure 4: Cohen's d bar chart, channels sorted by |d| (fine-structure).
    Colour indicates significance after Bonferroni correction.
    """
    channels   = fine_results['channels']
    order      = sorted(range(N_CHANNELS),
                        key=lambda i: abs(channels[i]['cohens_d']),
                        reverse=True)

    d_fine_ord = [channels[i]['cohens_d']     for i in order]
    d_env_ord  = [env_results['channels'][i]['cohens_d'] for i in order]
    sig_ord    = [channels[i]['significant']   for i in order]
    freq_ord   = [f"{CHANNEL_CENTRES_HZ[i]:.0f} Hz" for i in order]

    colors_fine = [C_BON if s else '#90CAF9' for s in sig_ord]
    colors_env  = [C_SPO if s else '#EF9A9A' for s in sig_ord]

    x = np.arange(N_CHANNELS)
    w = 0.4

    fig, ax = plt.subplots(figsize=(14, 4.5))
    ax.bar(x - w/2, d_fine_ord, w, color=colors_fine,
           label='Fine-structure', edgecolor='white', linewidth=0.3)
    ax.bar(x + w/2, d_env_ord,  w, color=colors_env,
           label='Envelope', edgecolor='white', linewidth=0.3,
           hatch='//')
    ax.axhline(0, color='black', lw=0.7)

    ax.set_xticks(x)
    ax.set_xticklabels(freq_ord, rotation=55, ha='right', fontsize=7)
    ax.set_ylabel("Cohen's $d$  (bonafide − spoof)")
    ax.set_title("Cohen's $d$ per Subband — Ranked by Discriminability\n"
                 "(Dark = significant after Bonferroni; "
                 "Light = not significant)",
                 fontsize=10)
    ax.legend(fontsize=9)
    ax.grid(True, axis='y', linestyle='--', alpha=0.4)
    fig.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved: {os.path.basename(out_path)}")

# =============================================================================
# SECTION 6 — Main
# =============================================================================

def main():
    print("=" * 65)
    print("01_exp1_kurtosis_separability.py")
    print("Experiment 1 — Kurtosis Separability Analysis")
    print("=" * 65)

    # Mount Drive (for protocol file and feature HDF5)
    from google.colab import drive
    drive.mount('/content/drive')

    # ------------------------------------------------------------------
    # Step 1: Download HDF5 from Google Drive
    # ------------------------------------------------------------------
    h5_local = os.path.join(LOCAL_DIR, "hos_features_train.h5")
    download_h5_from_drive("hos_features_train.h5", h5_local)

    # ------------------------------------------------------------------
    # Step 2: Parse protocol
    # ------------------------------------------------------------------
    labels = parse_train_protocol(DRIVE_PROTOCOL)

    # ------------------------------------------------------------------
    # Step 3: Load kurtosis from HDF5
    # ------------------------------------------------------------------
    print("\nExtracting kurtosis features from HDF5 ...")
    kurt_fine, kurt_env, y, utt_ids = load_kurtosis_from_h5(h5_local, labels)

    # ------------------------------------------------------------------
    # Step 4: Statistical analysis
    # ------------------------------------------------------------------
    print("\nRunning separability analysis ...")
    fine_results = separability_analysis(kurt_fine, y, 'fine_structure')
    env_results  = separability_analysis(kurt_env,  y, 'envelope')

    # Summary statistics
    n_sig_fine = sum(1 for c in fine_results['channels'] if c['significant'])
    n_sig_env  = sum(1 for c in env_results['channels']  if c['significant'])
    max_d_fine = max(abs(c['cohens_d']) for c in fine_results['channels'])
    max_d_env  = max(abs(c['cohens_d']) for c in env_results['channels'])

    print(f"\n{'='*65}")
    print(f"SUMMARY")
    print(f"{'='*65}")
    print(f"Fine-structure: {n_sig_fine}/{N_CHANNELS} channels significant "
          f"(Bonferroni α={fine_results['alpha_bonferroni']:.4f})")
    print(f"  Max |d| = {max_d_fine:.3f}")
    print(f"Envelope:       {n_sig_env}/{N_CHANNELS} channels significant")
    print(f"  Max |d| = {max_d_env:.3f}")

    # Best channel
    best_ch_idx = max(range(N_CHANNELS),
                      key=lambda i: abs(fine_results['channels'][i]['cohens_d']))
    best_ch = fine_results['channels'][best_ch_idx]
    print(f"\nMost discriminative channel: {best_ch_idx} "
          f"({CHANNEL_CENTRES_HZ[best_ch_idx]:.0f} Hz)  "
          f"d={best_ch['cohens_d']:.3f}  "
          f"mean_bon={best_ch['mean_bonafide']:.3f}  "
          f"mean_spo={best_ch['mean_spoof']:.3f}")

    # ------------------------------------------------------------------
    # Step 5: Save results JSON
    # ------------------------------------------------------------------
    results = {
        'experiment'         : 'Exp1_KurtosisSeparability',
        'n_utterances'       : int(len(y)),
        'n_bonafide'         : int((y == 0).sum()),
        'n_spoof'            : int((y == 1).sum()),
        'n_channels'         : N_CHANNELS,
        'channel_centres_hz' : [float(f) for f in CHANNEL_CENTRES_HZ],
        'bonferroni_alpha'   : float(fine_results['alpha_bonferroni']),
        'fine_structure'     : fine_results['channels'],
        'envelope'           : env_results['channels'],
        'summary': {
            'n_significant_fine' : n_sig_fine,
            'n_significant_env'  : n_sig_env,
            'max_abs_d_fine'     : round(max_d_fine, 4),
            'max_abs_d_env'      : round(max_d_env, 4),
            'best_channel_idx'   : best_ch_idx,
            'best_channel_hz'    : float(CHANNEL_CENTRES_HZ[best_ch_idx]),
            'best_channel_d'     : round(best_ch['cohens_d'], 4),
        }
    }

    json_path = os.path.join(LOCAL_DIR, "exp1_separability.json")
    with open(json_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved: exp1_separability.json")

    # ------------------------------------------------------------------
    # Step 6: Generate figures
    # ------------------------------------------------------------------
    print("\nGenerating figures ...")

    fig_cohens_d_heatmap(
        fine_results, env_results,
        os.path.join(LOCAL_DIR, "fig_01_01_cohens_d_heatmap.png"))

    fig_kurtosis_violin(
        kurt_fine, y, fine_results,
        os.path.join(LOCAL_DIR, "fig_01_02_kurtosis_violin.png"))

    fig_mean_profile(
        kurt_fine, kurt_env, y,
        os.path.join(LOCAL_DIR, "fig_01_03_kurtosis_meanprofile.png"))

    fig_cohens_d_barplot(
        fine_results, env_results,
        os.path.join(LOCAL_DIR, "fig_01_04_cohens_d_barplot.png"))

    # ------------------------------------------------------------------
    # Step 7: Upload all to Google Drive
    # ------------------------------------------------------------------
    print("\nUploading to Google Drive ...")
    for fname in [
        "exp1_separability.json",
        "fig_01_01_cohens_d_heatmap.png",
        "fig_01_02_kurtosis_violin.png",
        "fig_01_03_kurtosis_meanprofile.png",
        "fig_01_04_cohens_d_barplot.png",
    ]:
        save_to_drive(os.path.join(LOCAL_DIR, fname), fname)

    # --- Sync to ensure all writes are flushed ---
    print("\n[SYNC] Flushing file system buffers...")
    os.sync()
    print("[SYNC] Complete.")

    print("\n" + "=" * 65)
    print("Experiment 1 complete.")
    print(f"Fine-structure: {n_sig_fine}/{N_CHANNELS} channels significant  "
          f"max|d|={max_d_fine:.3f}")
    print(f"Envelope:       {n_sig_env}/{N_CHANNELS} channels significant  "
          f"max|d|={max_d_env:.3f}")
    print("=" * 65)


# =============================================================================
if __name__ == "__main__":
    main()